export enum TileType {
    None = 0,
    Ground = 1,
    GroundBorder = 3,
    ForestSmall = 5,
    MountainSmall = 7,
    WaterDeep = 9,
    WaterDeepSelected = 10,
    Water = 11,
    WaterSelected = 12,
    ForestBig = 13,
    MountainBig = 15,
    Town = 17,
    TownSelected = 18,
    Port = 19,
}
